### ISSUE TITLE
Modify user deleting logic

### ISSUE THREAD

**Issue by li-ang** [caicloud/harbor#55]
When someone deletes the users, the deleting logic is setting `deleted` field as `1` in `user` table . It can not delete user actually. We need to modify the user deleting logic for recreate the same user after deleting user.

**Comment by kdada** [comment]
Do you check the table `project` and `access_log`?
When a user is deleted, some tables will cascading delete relative records. But others do not. Please ensure it.

**Comment by li-ang** [comment]
closed
